### PR TITLE
Rename MANIFEST to MANIFEST.in and add licence and readme

### PR DESCRIPTION
**Pull request by bachp**
sdist is looking for MANIFEST.in in newer versions.
Also this adds the license file to the dist file on PyPi.

### CODE REVIEW

**Comment by MrYsLab** [comment]
Thanks for the pull request. I have merged the pull request. I am also changing the license from GNU GPL V3 to GNU AFFERO GPL V3 and that will be reflected in the next release.

**Comment by bachp** [comment]
@MrYsLab May I ask why choose to move to AGPL-3 instead of a more "free" license like MIT?

**Comment by MrYsLab** [comment]
The reason I picked Affero is that the Affero GPL is designed to close the so-called "application service provider loophole" in the GPL, which lets ASPs use GPL code without distributing their changes back to the open source community. I don't believe MIT protects me from this.

**Comment by bachp** [comment]
No MIT doesn't protect you from that ;) But it let's your work be used in far more scenarios like. But I fully respect your choice if you do not want that. Keep up the good work 👍

**Pull request merged**
